# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89b769abae51402284efa4d48f3450165e97a44097b3fdae101b6e7add2521c27e85120f29fb3ae540793e15193b590193593a45535f111c1c8ac4c95b2d59ed

test:
  secret_key_base: 4a7d2ff8db874a261b218634e6a03babc2e80bc7fc6dc91093537b3bf1b9ea5a2a4e5f3800094f30f853a3d102548a9b2aa1003000bce88b5531bd7c9746034e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
